AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World with SAM
Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs20.x
    Timeout: 5
Resources:
  eventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Handler: logger.handler
      Timeout: 3
      Events:
        GetLogs:
          Type: Api
          Properties:
            Path: /logs
            Method: get
        FileUpload:
          Type: S3
          Properties:
            Bucket:
              Ref: myBucket
            Events: s3:ObjectCreated:*
      CodeUri: s3://sam-felippe-mozer/cf00a33f16b423babb71dc2b6a721715
  myBucket:
    Type: AWS::S3::Bucket
  addNumbers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: add.handler
      Events:
        GetLogs:
          Type: Api
          Properties:
            Path: /add
            Method: post
      CodeUri: s3://sam-felippe-mozer/cf00a33f16b423babb71dc2b6a721715
